sudo: required
os: linux
dist: trusty
language: php
php: 7.1

addons:
   chrome: stable

branches:
  only:
  - example

services:
- mysql

env:
  global:
    APP_URL: http://localhost:8000
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: shopcart
    DB_USERNAME: root
    DB_PASSWORD: password

before_install:
- mysql -e "CREATE DATABASE ${DB_DATABASE} DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;"
- mysql -e "SET PASSWORD = PASSWORD('${DB_PASSWORD}');"

install:
- cp .env.example .env
- composer install --no-interaction --prefer-dist --no-suggest

before_script:
- php artisan key:generate
- php artisan migrate --force
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- php artisan serve &

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit --coverage-clover=coverage.xml
- php artisan dusk

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - vendor
